-- Abfrage von Küba-emails, welche als bevorzugte email im Master genutzt werden.
--
WITH kuba_data AS 
(
	SELECT DISTINCT
		CMP.X_COMPLEX_NO,
		CMP.COMPANY_NO,
		EJJ.JOIN_NO kuba_join_no,
		CMP.COMPANY_NR,
		XKD.JOIN_NR kuba_join,
		CMP.DISPLAY_NAME
--		ADR.CHANNEL_VALUE email_address,
--		ADR.IS_DEFAULT_ADDRESS
	FROM BSI_X_EXT_KUBA_DATA xkd 
		INNER JOIN BSI_X_EXT_JOIN_JOIN ejj
			INNER JOIN BSI_X_EXT_JOIN ej 
			ON EJ.EXT_JOIN_NR = EJJ.EXT_JOIN_NR
			AND EJ.EXT_JOIN_TYPE_UID = EJJ.EXT_JOIN_TYPE_UID
			INNER JOIN BSI_COMPANY cmp
			ON CMP.COMPANY_NR = EJJ.JOIN_NR
			INNER JOIN BSI_X_ADDRESS_MAPPING adm
--				INNER JOIN BSI_ADDRESS adr
--				ON ADR.ADDRESS_NR = ADM.ADDRESS_NR
			ON ADM.EXT_JOIN_NR = EJJ.EXT_JOIN_NR
--			AND ADM.JOIN_TYPE_UID = 318594
		ON EJJ.EXT_JOIN_NR = XKD.JOIN_NR
--	WHERE ADR.CHANNEL_UID = 113641
	--AND CMP.COMPANY_NR = 4951486493 -- Keine KUBA-email 19101387, MIT KUBA-email: 4951486493 (Company_NO = 1440917)
	WHERE EJJ.IS_MASTER = 0
	AND EJ.INTERFACE_UID NOT IN (108187, 108205) -- samba / nxdsmp, Küba: 131309
	AND EJ.ACTIVE = 1
--	AND ADR.CHANNEL_VALUE IS NOT NULL
	ORDER BY CMP.COMPANY_NO
),
master_data AS 
(
	SELECT DISTINCT
		CMP.X_COMPLEX_NO,
		CMP.COMPANY_NO,
		ejj.JOIN_NO,
		CMP.COMPANY_NR,
		CMP.DISPLAY_NAME
--		ADR.CHANNEL_VALUE email_address
	FROM BSI_X_EXT_JOIN ej 
		INNER JOIN BSI_X_EXT_JOIN_JOIN ejj
			INNER JOIN BSI_COMPANY cmp
--				INNER JOIN BSI_ADDRESS adr
--				ON ADR.ITEM_KEY0_NR = CMP.COMPANY_NR
			ON CMP.COMPANY_NR = EJJ.JOIN_NR
		ON EJJ.EXT_JOIN_NR = EJ.EXT_JOIN_NR
		AND EJJ.EXT_JOIN_TYPE_UID = EJ.EXT_JOIN_TYPE_UID
--	WHERE ADR.CHANNEL_UID = 113641
--	AND ADR.IS_DEFAULT_ADDRESS = 1
	WHERE EJJ.IS_MASTER = 1
	AND EJ.INTERFACE_UID IN (108187, 108205) -- samba / nxdsmp
	and ej.active = 1
)
SELECT DISTINCT 
	KBD.X_COMPLEX_NO,
	MDT.JOIN_NO master_join_no,
	KBD.COMPANY_NR,
--	KBD.COMPANY_NO,
	KBD.kuba_join_no,
	KBD.DISPLAY_NAME kuba_company_name
--	KBD.email_address kuba_mail,
--	MDT.email_address master_mail
FROM kuba_data KBD
	INNER JOIN master_data MDT
	ON MDT.COMPANY_NR = KBD.COMPANY_NR
	ORDER BY KBD.X_COMPLEX_NO
--WHERE MDT.email_address = KBD.email_address
;
