-- SUCCESS
DECLARE
	l_text varchar(32767) := NULL;
	total_count int := 0;
	added_count int := 0;
BEGIN
	FOR cur_rec IN (
		SELECT BDOC.X_LOCATION_LOB FROM BSI_DOCUMENT BDOC
			WHERE DOC.ITEM_KEY0_NR = 19062485
	) LOOP

	total_count := total_count + 1;

	IF l_text IS NULL THEN
		l_text := cur_rec.X_LOCATION_LOB;
	ELSE
		IF LENGTH(l_text) < 32000 THEN
			l_text := l_text || ', ' || cur_rec.X_LOCATION_LOB;
			added_count := added_count + 1;
		END IF;
	END IF;
	END LOOP;

	IF added_count < total_count THEN
		l_text := l_text || ' .. ' || added_count || ' Links added from Total ' || total_count || '.';
	END IF;

	dbms_output.put_line(l_text);
END;


SELECT 
	BC.X_EXT_JOIN_NR,
	TO_CHAR(BC.EVT_START, 'DD.MM.YYYY HH24:MI') starttermin,
	BC.COMMUNICATION_NR,
	BC.RESPONSIBLE_USER_NR,
	BDOC.X_LOCATION_LOB,
	BDOC.DOCUMENT_TYPE_UID
FROM BSI_COMMUNICATION bc
INNER JOIN BSI_DOCUMENT BDOC 
ON BDOC.X_EXT_JOIN_NR = BC.X_EXT_JOIN_NR
WHERE BDOC.X_EXT_JOIN_NR = 1545609 -- 3413377957 -- 19062485
--WHERE BDOC.ITEM_KEY0_NR = 19561007
--AND BC.RESPONSIBLE_USER_NR = 10
;


SELECT 
	BXEJJ.JOIN_NR, 
	BXEJJ.JOIN_NO,
	BXEJJ.EXT_JOIN_NR
FROM BSI_X_EXT_JOIN_JOIN bxejj 
WHERE BXEJJ.JOIN_NO = 1464506
--WHERE BXEJJ.EXT_JOIN_NR = 1545609
;
SELECT * FROM BSI_DOCUMENT bd 
WHERE BD.ITEM_KEY0_NR = 21390199
;
SELECT * FROM BSI_COMMUNICATION bc
WHERE BC.X_EXT_JOIN_NR = 1010247583 -- 21390199
;
SELECT * FROM BSI_COMMUNICATION bc WHERE BC.COMMUNICATION_NR = 3395422962 -- 3401628966
;
SELECT * FROM BSI_DOCUMENT bd WHERE BD.ITEM_KEY0_NR = 3395422962 -- 3401628966
;


-------------------
-- OK
-------------------
--
SELECT * FROM (
SELECT 
	CMC.X_EXT_JOIN_NR,
	TO_CHAR(CMC.EVT_START, 'DD.MM.YYYY HH24:MI') starttermin,
	CMC.COMMUNICATION_NR,
	CMC.RESPONSIBLE_USER_NR,
	BDOC.X_LOCATION_LOB,
	BDOC.DOCUMENT_TYPE_UID
FROM BSI_COMMUNICATION CMC
INNER JOIN BSI_DOCUMENT BDOC 
--	INNER JOIN BSI_X_EXT_JOIN_JOIN ejj ON EJJ.EXT_JOIN_NR = BDOC.X_EXT_JOIN_NR
ON BDOC.ITEM_KEY0_NR = CMC.COMMUNICATION_NR
--WHERE BDOC.X_EXT_JOIN_NR = 22130418 --1442539 -- 1545609
--WHERE CMC.X_EXT_JOIN_NR = 5199712056
WHERE bdoc.ITEM_KEY0_NR = 4823232737
)
WHERE rownum < 1000
;
------------------
-- VertragMyCampaignsSearchLutzGärten.pdf,image001.jpg,AW Google Ads Prof 12 MT.eml


SELECT * FROM (
	SELECT DISTINCT
		TO_CHAR(CMC.EVT_START, 'DD.MM.YYYY HH24:MI') starttermin,
		CMC.COMMUNICATION_NR,
		CMC.RESPONSIBLE_USER_NR,
		TO_CHAR(BCS.EVT_START, 'DD.MM.YYYY') case_start,
		(
			SELECT
				SUBSTR(LISTAGG(dbms_lob.substr(XDOC.X_LOCATION_LOB, 2000, 1), '|') within GROUP(ORDER BY XDOC.X_LOCATION_LOB), 0, 3000)
			FROM BSI_DOCUMENT xdoc
			WHERE XDOC.ITEM_KEY0_NR = CMC.COMMUNICATION_NR
		) doc_links,
		BDOC.DOCUMENT_TYPE_UID
	FROM BSI_CASE bcs 
	INNER JOIN BSI_COMMUNICATION CMC
		INNER JOIN BSI_DOCUMENT BDOC 
		--	INNER JOIN BSI_X_EXT_JOIN_JOIN ejj ON EJJ.EXT_JOIN_NR = BDOC.X_EXT_JOIN_NR
		ON BDOC.ITEM_KEY0_NR = CMC.COMMUNICATION_NR
--	ON cmc.RESPONSIBLE_USER_NR = BCS.PERSON_NR
	ON cmc.CASE_FRAME_NR = BCS.CASE_FRAME_NR
	--WHERE BDOC.X_EXT_JOIN_NR = 22130418 --1442539 -- 1545609
	--WHERE CMC.X_EXT_JOIN_NR = 5199712056
	WHERE bdoc.ITEM_KEY0_NR = 4823232737
)
WHERE rownum < 1000
;




SELECT COUNT(*) anzahl FROM BSI_CASE bc
;
-- 2078531

WITH preselect AS 
(
	SELECT
		CSE.X_COMPANY_NR
	FROM BSI_CASE cse 
	WHERE CSE.X_COMPANY_NR NOT IN (
		SELECT BXEJJ.JOIN_NR FROM BSI_X_EXT_JOIN_JOIN bxejj
	)
)
SELECT
	COUNT(*) anzahl
FROM preselect psel
WHERE psel.X_COMPANY_NR NOT IN (
	SELECT BXEJJ.OLD_JOIN_NR FROM BSI_X_EXT_JOIN_JOIN bxejj
)
;
-- 1908649
-- 170522

SELECT
	COUNT(*) anzahl
FROM BSI_CASE cse 
WHERE CSE.X_COMPANY_NR NOT IN (
	SELECT CMP.COMPANY_NR FROM BSI_COMPANY cmp
)
;
-- 170502

SELECT UCT.TEXT, CMC.STATUS_UID, BDOC.* 
FROM BSI_DOCUMENT bdoc 
	INNER JOIN BSI_COMMUNICATION cmc
		INNER JOIN BSI_UC_TEXT uct ON UCT.UC_UID = CMC.STATUS_UID AND UCT.LANGUAGE_UID = 246
	ON CMC.COMMUNICATION_NR = BDOC.ITEM_KEY0_NR
--WHERE BDOC.X_LOCATION_LOB LIKE 'GE11F TGDBEJOA RE Vos inscriptions chez local.ch  Numéro de client 1002244291%'
WHERE BDOC.DOCUMENT_NR = 7240270405 
;

SELECT DISTINCT STATUS_UID FROM BSI_COMMUNICATION bc
;
-- 0, 3512, 3513, 111957

SELECT
	COUNT(*) anzahl
FROM INTF_CONFIG_MAPPING icm 
WHERE ICM.JOIN_NR NOT IN (
	SELECT CSE.X_COMPANY_NR FROM BSI_CASE cse
)
;

SELECT 
	COUNT(*) anzahl
FROM BSI_COMPANY cmp 
WHERE cmp.COMPANY_NR NOT IN (
	SELECT CSE.X_COMPANY_NR FROM BSI_CASE cse
)
;
-- 719587



SELECT  DISTINCT ITEM_TYPE_ID FROM BSI_DOCUMENT bd
;
-- 0,106064,108756,111951,128545,137721,318594,318596,318597,318598,318600


SELECT COUNT(*) FROM BSI_COMMUNICATION bc WHERE BC.RESPONSIBLE_USER_NR IS NULL
;
-- 0, nada! KEIN!