SELECT COUNT(*) anzahl FROM BSI_CASE cse
WHERE CSE.X_COMPANY_NR IS NOT NULL
;
-- 2079447

SELECT COUNT(*) anzahl FROM BSI_CASE cse
INNER JOIN BSI_X_OFFER xof ON XOF.CASE_NR = CSE.CASE_NR
WHERE CSE.X_COMPANY_NR IS NOT NULL
;
-- 15123

SELECT COUNT(*) anzahl FROM BSI_CASE cse
INNER JOIN BSI_X_LEAD xof ON XOF.CASE_NR = CSE.CASE_NR
WHERE CSE.X_COMPANY_NR IS NOT NULL
;
-- 3666

SELECT COUNT(*) anzahl FROM BSI_CASE cse
INNER JOIN BSI_X_BACK_OFFICE_ASSIGNMENT xof ON XOF.CASE_NR = CSE.CASE_NR
WHERE CSE.X_COMPANY_NR IS NOT NULL
;
-- 200699

SELECT COUNT(*) anzahl FROM BSI_CASE cse
INNER JOIN BSI_EMAIL_MESSAGE xof ON XOF.CASE_NR = CSE.CASE_NR
WHERE CSE.X_COMPANY_NR IS NOT NULL
;
-- 134814

SELECT COUNT(*) anzahl FROM BSI_CASE cse
INNER JOIN BSI_CASE_STEP_ITEM xof ON XOF.CASE_NR = CSE.CASE_NR
WHERE CSE.X_COMPANY_NR IS NOT NULL
;
-- 418510

SELECT COUNT(*) anzahl FROM BSI_CASE cse
INNER JOIN BSI_CASE_STEP xof ON XOF.CASE_NR = CSE.CASE_NR
WHERE CSE.X_COMPANY_NR IS NOT NULL
;
-- 15955447

SELECT * FROM BSI_UC_TEXT uct WHERE UCT.UC_UID = 318766 AND UCT.LANGUAGE_UID = 246
;

