SET SERVEROUTPUT ON SIZE 100000;

DECLARE
	match_count INTEGER;
BEGIN
	FOR t IN (
		SELECT atc.OWNER, ATC.TABLE_NAME, ATC.COLUMN_NAME
		FROM SYS.ALL_TAB_COLUMNS atc
		WHERE upper(ATC.OWNER) = 'BSICRM'
		AND upper(ATC.TABLE_NAME) = 'BSI_COMMUNICATION'
		and ATC.DATA_TYPE = 'NUMBER'
	) LOOP

	EXECUTE IMMEDIATE
		'SELECT COUNT(*) FROM ' || t.owner || '.' || t.table_name ||
		' WHERE '||t.column_name||' = :1'
		INTO match_count
		USING '1001596138';

	IF match_count > 0 THEN
		dbms_output.put_line( t.table_name ||' '||t.column_name||' '||match_count );
	END IF;
	dbms_output.put_line( t.table_name ||' '||t.column_name );
END LOOP;

END;



SELECT * FROM (
	SELECT CMC.X_COMMUNICATION_EXT_KEY FROM BSI_COMMUNICATION cmc
) WHERE rownum < 20
;

SELECT CMP.COMPANY_NR, CMP.X_COMPLEX_NO FROM BSI_COMPANY cmp WHERE CMP.COMPANY_NO = 9
;

SELECT
	cmc.company_nr,
	count(CMC.X_COMMUNICATION_EXT_KEY) Anzahl
FROM BSI_COMMUNICATION cmc
GROUP BY CMC.COMPANY_NR
HAVING count(CMC.X_COMMUNICATION_EXT_KEY) > 1
;

SELECT
	cmc.company_nr,
	CMC.X_COMMUNICATION_EXT_KEY
FROM BSI_COMMUNICATION cmc
WHERE CMC.COMPANY_NR = 19061374
;
--1022f0cb-a77f-40d8-8ce3-72e7c7b0d398
--COMPANY_NR	X_COMMUNICATION_EXT_KEY
--19061374		06adca04-cf96-4f6a-bf3f-a68377164478
--19061374		1022f0cb-a77f-40d8-8ce3-72e7c7b0d398
--19061374		38A18B602DEF6BF5E053C020A60A91BB

SELECT
	cmc.company_nr,
	CMC.X_COMMUNICATION_EXT_KEY
FROM BSI_COMMUNICATION cmc
	INNER JOIN EXT_COMMUNICATION ecm 
	ON ECM.COMMUNICATION_EXT_KEY = CMC.X_COMMUNICATION_EXT_KEY
WHERE CMC.COMPANY_NR = 19061374
;



SELECT * FROM BSI_COMMUNICATION cmc WHERE CMC.X_COMMUNICATION_EXT_KEY = '3e37d08d69fb4e9d80f79be3c0699436'
;
--0000107a-e645-446a-96f3-e6ab00d7549a
--00FD50B6-AE9A-460C-AB60-DE7CF9D489BE

SELECT
	DOC.DOCUMENT_NR,
	dbms_lob.substr(DOC.X_LOCATION_LOB, 1000, 1) doc_url,
	DOC.DOCUMENT_TYPE_UID,
	UC_DOCTYPE.TEXT doc_type,
	doc.X_INTERFACE_UID,
	UC_INTERFACE.TEXT interface_desc
FROM BSI_DOCUMENT doc
INNER JOIN BSI_UC_TEXT uc_interface ON UC_INTERFACE.UC_UID = DOC.X_INTERFACE_UID AND UC_INTERFACE.LANGUAGE_UID = 246
INNER JOIN BSI_UC_TEXT uc_doctype ON UC_DOCTYPE.UC_UID = DOC.DOCUMENT_TYPE_UID AND UC_DOCTYPE.LANGUAGE_UID = 246
WHERE DOC.X_INTERFACE_UID NOT IN (109418)
--WHERE dbms_lob.substr(DOC.X_LOCATION_LOB, 250, 1) 
--LIKE 'https://dokuarchiv.ltv.ch/w2p2/default.asp?wdSearchCmd=lb_0$*idx_dwInteger00$*op_1$*val_9$*rb_0&SetObjectType=0&Redirect2GUI=1&SearchOnly=1&ShowGUIOnly=0%'
;
-- DOCUMENT_NR = 67570412

SELECT * FROM BSI_DOCUMENT doc
INNER JOIN BSI_UC_TEXT uc_interface ON UC_INTERFACE.UC_UID = DOC.X_INTERFACE_UID AND UC_INTERFACE.LANGUAGE_UID = 246
INNER JOIN BSI_UC_TEXT uc_doctype ON UC_DOCTYPE.UC_UID = DOC.DOCUMENT_TYPE_UID AND UC_DOCTYPE.LANGUAGE_UID = 246
WHERE dbms_lob.substr(DOC.X_LOCATION_LOB, 100, 1) 
LIKE 'https://dokuarchiv.ltv.ch/w2p2%'
;

SELECT 
	UCT.UC_UID, UCT.TEXT, UC.CODE_TYPE, UC.PARENT_UID 
FROM BSI_UC uc INNER JOIN BSI_UC_TEXT uct ON UCT.UC_UID = UC.UC_UID 
WHERE UC.UC_UID IN (318766)
AND UCT.LANGUAGE_UID = '246'
;