SELECT * from BSI_X_ADDRESS_MAPPING 
WHERE EXT_JOIN_NR IN (
	SELECT ext_join_nr from bsi_x_address_mapping group by EXT_JOIN_NR, JOIN_TYPE_UID, TYPE_UID, CHANNEL_UID having count(*) > 1
);

SELECT * FROM BSI_UC_TEXT WHERE UC_UID = '6906248382';

SELECT UCT.UC_UID, UCT.TEXT, UCT.LANGUAGE_UID, uc.CODE_TYPE FROM BSI_UC uc INNER JOIN BSI_UC_TEXT uct ON UCT.UC_UID = UC.UC_UID 
WHERE UCT.UC_UID IN (6906248382)
AND UCT.LANGUAGE_UID = '246';

SELECT UCT.TEXT, uc.* FROM BSI_UC uc INNER JOIN BSI_UC_TEXT uct ON UCT.UC_UID = UC.UC_UID 
WHERE UC.CODE_TYPE in (143811)
AND UC.IS_ACTIVE = 1
AND UCT.LANGUAGE_UID = '246';

SELECT UCT.UC_UID, UCT.TEXT, UCT.LANGUAGE_UID, uc.CODE_TYPE FROM BSI_UC uc INNER JOIN BSI_UC_TEXT uct ON UCT.UC_UID = UC.UC_UID 
WHERE UCT.UC_UID IN (143892)
AND UCT.LANGUAGE_UID = '246';

SELECT * FROM intf_config_mapping WHERE JOIN_NR = 139787 -- 108994
;

SELECT * FROM BSI_UC_STEP WHERE STEP_UID = '2757013308';
SELECT * FROM BSI_UC_STEP_CONFIGURATION WHERE STEP_CONFIGURATION_UID = '2706214961';
SELECT * FROM BSI_UC_STEP_DECISION WHERE STEP_DECISION_UID = '2757013308';