SELECT * FROM BSI_X_REST_SYNC_ITEM
WHERE ROOT_ITEM_TYPE_ID IN (318594, 318596)
ORDER BY ITEM_KEY0_NR, ITEM_TYPE_ID, ROOT_ITEM_KEY0_NR, ROOT_ITEM_TYPE_ID
;

SELECT CMP.COMPANY_NO, CMP.COMPANY_NR FROM BSI_LEGAL_ENTITY_VIEW lev 
	INNER JOIN BSI_COMPANY cmp 
	ON CMP.X_COMPLEX_NO = LEV.X_COMPLEX_NO
;

SELECT * FROM BSI_COMPANY cmp 
WHERE X_COMPLEX_NO NOT IN (
	SELECT DISTINCT X_COMPLEX_NO FROM BSI_LEGAL_ENTITY_VIEW
)
;

-- 108224 /* External Company */, 318594 /* Company */, 318596 /* Person */
SELECT LEV.* FROM BSI_LEGAL_ENTITY_VIEW lev
WHERE X_COMPLEX_NO NOT IN (
	SELECT DISTINCT X_COMPLEX_NO FROM BSI_COMPANY cmp 
	INNER JOIN BSI_X_EXT_JOIN_JOIN ejj 
	ON EJJ.JOIN_NR = CMP.COMPANY_NR
	AND EJJ.EXT_JOIN_TYPE_UID = '318594'
--	AND EJJ.EXT_JOIN_TYPE_UID = '318596'
--	AND EJJ.EXT_JOIN_TYPE_UID = '108224'
--	AND EJJ.EXT_JOIN_TYPE_UID in ('318596', '318594', '108224')
)
AND LEV.COMPANY_NR <> 0
;

SELECT * FROM bsicrm.BSI_X_REST_SYNC_ITEM
WHERE ITEM_TYPE_ID = 318594 AND ROOT_ITEM_TYPE_ID = 318594 
AND NOT EXISTS (SELECT 0 FROM bsicrm.BSI_COMPANY xcm WHERE XCM.COMPANY_NR = ROOT_ITEM_KEY0_NR);
