
SELECT
	count(CMP.X_COMPLEX_NO) anzahl
FROM S2_EM_PRODUCT_CONDENSED_IN semp 
	INNER JOIN BSI_COMPANY cmp
		INNER JOIN BSI_X_EXT_JOIN_JOIN ejj 
			INNER JOIN BSI_X_EXT_JOIN ej 
			ON EJ.EXT_JOIN_NR = EJJ.EXT_JOIN_NR
			AND EJ.EXT_JOIN_TYPE_UID = EJJ.EXT_JOIN_TYPE_UID
		ON EJJ.JOIN_NR = CMP.COMPANY_NR
	ON EJJ.JOIN_NO = SEMP.NXCUSTOMERID
;

SELECT
	CMP.X_COMPLEX_NO,
	SEMP."NO" "ENTRY-ID"
FROM S2_EM_PRODUCT_CONDENSED_IN semp 
	INNER JOIN BSI_COMPANY cmp
		INNER JOIN BSI_X_EXT_JOIN_JOIN ejj 
			INNER JOIN BSI_X_EXT_JOIN ej 
			ON EJ.EXT_JOIN_NR = EJJ.EXT_JOIN_NR
			AND EJ.EXT_JOIN_TYPE_UID = EJJ.EXT_JOIN_TYPE_UID
		ON EJJ.JOIN_NR = CMP.COMPANY_NR
	ON EJJ.JOIN_NO = SEMP.NXCUSTOMERID
;
