SELECT DISTINCT COMPLAINT_SOLUTION_UID FROM BSI_X_COMPLAINT
;

SELECT
	COUNT(CSE.PROCESS_UID) Anzahl,
	CSE.CASE_NR
FROM BSI_X_CASE_COMPLAINT xcc 
INNER JOIN BSI_CASE cse ON CSE.CASE_NR = XCC.CASE_NR
GROUP BY CSE.CASE_NR
--HAVING COUNT(CSE.PROCESS_UID) > 1
;

SELECT DISTINCT
	XCPL.COMPLAINT_NO,
	XCPL.EVT_ISSUED,
	XCPL.SUBJECT,
	XUCT.TEXT status,
	XCPL.RESPONSIBLE_UID,
	XCPL.EVT_DUE,
	XCPL.COMPANY_NR,
	XCPL.CONTRACT_NR,
	XCPL.INVOICE_NR,
	REPLACE(dbms_lob.substr(XCPL.DESCRIPTION, 100, 1), ';', '') description,
	REPLACE(dbms_lob.substr(XCPL.SOLUTION_NOTES, 100, 1), ';', '') solution_notes,
	XCPL.CREATE_CASE_NR,
	(
		SELECT CASE WHEN ICSA.STATUS_UID != 75959 THEN
			0
		ELSE 
			XCPL.COMPLAINT_NR 
		END 
		FROM BSI_CASE ICSA
		WHERE ICSA.CASE_NR = MCC.CASE_NR
	) AS update_complaint_nr
FROM BSI_X_COMPLAINT xcpl 
	INNER JOIN BSI_X_CASE_COMPLAINT mcc 
		INNER JOIN BSI_CASE CSE
			INNER JOIN BSI_UC_TEXT uct 
			ON UCT.UC_UID = CSE.STATUS_UID
			AND UCT.LANGUAGE_UID = 246
		ON CSE.CASE_NR = MCC.CASE_NR
		AND CSE.STATUS_UID IN (75959)
	ON MCC.COMPLAINT_NR = XCPL.COMPLAINT_NR
	INNER JOIN BSI_UC_TEXT xuct
	ON XUCT.UC_UID = XCPL.STATUS_UID
	AND XUCT.LANGUAGE_UID = 246
WHERE XCPL.COMPANY_NR > 0
AND XCPL.STATUS_UID IN (109053, 119170)
--109053	Abgeschlossen
--119170	Abgeschlossen
--128898	Warten auf Rückmeldung
AND XCPL.EVT_ISSUED > to_date('31.12.2017', 'dd.mm.yyyy')
--AND XCPL.EVT_DUE < (
--	SELECT end_date FROM date_range
--)
ORDER BY XCPL.COMPANY_NR, XCPL.COMPLAINT_NO
;
