-- Personen, welche einer Küba-Firma angehören
--
SELECT
	COUNT(DISTINCT CPS.PERSON_NR) AS kuba_personen
FROM BSI_X_EXT_KUBA_DATA kbd 
	INNER JOIN BSI_X_EXT_JOIN_JOIN ejj
		INNER JOIN BSI_X_EXT_JOIN ej ON EJ.EXT_JOIN_NR = EJJ.EXT_JOIN_NR
		AND EJ.INTERFACE_UID IN (131309, 131308) -- KuBa company data, Küba
		AND EJ.INTERFACE_UID NOT IN (108187, 108205) -- samba / nxdsmp, Küba: 131309
		AND EJ.ACTIVE = 1
		AND EJ.EXT_JOIN_TYPE_UID = 108224  -- External Company
		AND EJ.EXT_JOIN_TYPE_UID = EJJ.EXT_JOIN_TYPE_UID
	INNER JOIN BSI_COMPANY_PERSON cps
		INNER JOIN BSI_PERSON prs ON PRS.PERSON_NR = CPS.PERSON_NR
		AND PRS.IS_ACTIVE = 1
		INNER JOIN BSI_X_EXT_JOIN_JOIN pjj 
			INNER JOIN BSI_X_EXT_JOIN pj ON PJ.EXT_JOIN_NR = PJJ.EXT_JOIN_NR
			AND PJ.EXT_JOIN_TYPE_UID = 108236  -- External Person
			AND PJ.INTERFACE_UID in (131310, 131308)  -- KuBa person data, KüBa
			AND PJ.ACTIVE = 1
		ON PJJ.JOIN_NR = CPS.PERSON_NR
	ON CPS.COMPANY_NR = EJJ.JOIN_NR
	ON EJJ.EXT_JOIN_NR = KBD.JOIN_NR
;
-- 324981


-- Alle zu einer Firma gehörenden Personen 
--
SELECT
	COUNT(DISTINCT CPS.PERSON_NR) AS personen_zu_firma
FROM BSI_X_EXT_JOIN_JOIN ejj
	INNER JOIN BSI_X_EXT_JOIN ej ON EJ.EXT_JOIN_NR = EJJ.EXT_JOIN_NR
	AND EJ.EXT_JOIN_TYPE_UID = 108224  -- External Company
	AND EJ.ACTIVE = 1
	AND EJ.EXT_JOIN_TYPE_UID = EJJ.EXT_JOIN_TYPE_UID
	INNER JOIN BSI_COMPANY_PERSON cps
		INNER JOIN BSI_PERSON prs ON PRS.PERSON_NR = CPS.PERSON_NR
		AND PRS.IS_ACTIVE = 1
		INNER JOIN BSI_X_EXT_JOIN_JOIN pjj 
			INNER JOIN BSI_X_EXT_JOIN pj ON PJ.EXT_JOIN_NR = PJJ.EXT_JOIN_NR
			AND PJ.EXT_JOIN_TYPE_UID = 108236  -- External Person
--			AND PJ.INTERFACE_UID IN (131310, 131308, 108187)
			AND PJ.ACTIVE = 1
		ON PJJ.JOIN_NR = CPS.PERSON_NR
	ON CPS.COMPANY_NR = EJJ.JOIN_NR
;
-- 680796


SELECT count(DISTINCT EJJ.JOIN_NO) AS Anzahl
FROM BSI_X_EXT_KUBA_DATA xkd 
	INNER JOIN BSI_X_EXT_JOIN_JOIN ejj
		INNER JOIN BSI_X_EXT_JOIN ej 
		ON EJ.EXT_JOIN_NR = EJJ.EXT_JOIN_NR
		AND EJ.EXT_JOIN_TYPE_UID = EJJ.EXT_JOIN_TYPE_UID
	ON EJJ.EXT_JOIN_NR = XKD.JOIN_NR
WHERE EJJ.IS_MASTER = 0
AND EJ.INTERFACE_UID NOT IN (108187, 108205) -- samba / nxdsmp, Küba: 131309
AND EJ.ACTIVE = 1
;
-- 345969
